version: '3.8'

services:
  cccd-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - PORT=3000
      - HOST=0.0.0.0
    volumes:
      - ./logs:/app/logs
      - ./output:/app/output
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - cccd-network

  cccd-dev:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - PORT=3000
      - HOST=0.0.0.0
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - ./output:/app/output
    command: ["node", "src/main.js", "api"]
    restart: unless-stopped
    networks:
      - cccd-network

networks:
  cccd-network:
    driver: bridge

volumes:
  logs:
  output: